import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Barlow_Condensed } from 'next/font/google';

export const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});

export const barlowCondensed = Barlow_Condensed({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-barlow',
});

export const metadata: Metadata = {
  title: "Artistle - Guess the Artist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${barlowCondensed.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
